### ISSUE TITLE
`AuthorURI` vs. `Author URI` in plugin header documentation (and code?)

### ISSUE THREAD

**Issue by tyrann0us** [inpsyde/modularity#14]
**Describe the bug**
At least in the documentation (https://github.com/inpsyde/modularity/blob/master/docs/Properties.md) and the release notes for `v1.3.0` (https://github.com/inpsyde/modularity/releases/tag/1.3.0) `AuthorURI` is mentioned as one of the plugin headers. However, similar to the theme headers, it is `Author URI` (with whitespace), see https://developer.wordpress.org/plugins/plugin-basics/header-requirements/#header-fields.

**Expected behavior**
All examples should use the official plugin header `Author URI` instead of `AuthorURI`.

**Additional context**
I haven't checked the actual code, so I don't know if this is just a typo in the documentation or if the code actually doesn't support `Author URI`.

**Comment by Chrico** [comment]
It's a bit missleading. If we look at https://developer.wordpress.org/reference/functions/get_plugin_data/ we can see, that the header value is `Author URI`, but it will be mapped in `get_plugin_data()` to `AuthorURI`.

So yes, it seems the documentation is a bit missleading here. We need to re-check the table in https://github.com/inpsyde/modularity/blob/master/docs/Properties.md - seems the "Plugin - file header" are showing the results comming from `get_plugin_data()` and not the inputs comming from the file header.

**Comment by tyrann0us** [comment]
LGTM. Haven't tested this though. Closing this, thanks!
