### ISSUE TITLE
[Bug]: Tests fail on PHP 8.2

### ISSUE THREAD

**Issue by esurov** [inpsyde/modularity#30]
### Description of the bug

Running tests with PHP 8.2 I'm getting an error:
Error:         This version of PHPUnit does not support code coverage on PHP 8

Also some tests fail out of the box:

1) Inpsyde\Modularity\Tests\Unit\Properties\PluginPropertiesTest::testIsMuPlugin with data set "is not mu-plugin" ('/wp-content/plugins/the-plugin/', '/wp-content/mu-plugins/', false)

2) Inpsyde\Modularity\Tests\Unit\Properties\PluginPropertiesTest::testIsMuPlugin with data set "is mu-plugin" ('/wp-content/mu-plugins/the-plugin/', '/wp-content/mu-plugins/', true)

### Reproduction instructions

1. git clone https://github.com/inpsyde/modularity.git
2. cd modularity
3. composer install
4. vendor/phpunit/phpunit/phpunit

### Expected behavior

All unit tests pass

### Environment info

- dev-master
- php 8.2.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esurov** [comment]
Failed tests problem was fixed by changing permissions to `/tmp/xdebug.log` file with `chmod a+w /tmp/xdebug.log` but the coverage problem persists:

```
Error: This version of PHPUnit does not support code coverage on PHP 8
```

**Comment by esurov** [comment]
This issue could be fixed by merging my PR: https://github.com/inpsyde/modularity/pull/31

**Comment by Chrico** [comment]
#31 was merged. I'm going to close this issue now. 💪🏻
