### ISSUE TITLE
[Feature Request]: Fire an event when building with a generic hook name to be able to target it easily  

### ISSUE THREAD

**Issue by luislard** [inpsyde/modularity#47]
### Is your feature request related to a problem?

Currently, the only way to add modules from other places is via adding an action to [this hook](https://github.com/inpsyde/modularity/blob/7ace0e8f9b9ce0f07777d461f478c62b7e14fefe/src/Package.php#L369)

The hook name is created dynamically based on the package name.

Since #44 was merged it would be very nice to have a way to add a module with an extension to all packages automatically.

So, in a project with many packages we could do:

```PHP
add_action('inpsyde.modularity.package.init', fn($package) => $package->addModule($moduleWithExtensionByType));
```

### Describe the desired solution

Maybe the solution is to add a hook.

### Describe the alternatives that you have considered

Option 1:
Adding a generic hook

Option 2:
Using current hookName is also an option but you should hook in another hook like

```PHP
function addExtensionCb (){
    /* some logic parsing current_action() name with startsWith inpsyde.modularity and endWith init */
}

add_action('muplugins_loaded', function(){
    add_action('all', 'addExtensionCb');
}, PHP_INT_MIN);

add_action('plugins_loaded', function(){
    remove_action('all', 'addExtensionCb');
}, PHP_INT_MAX)

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Chrico** [comment]
While I maybe agree with having a "generic" hookName to hook into _all_ Packages, this could also introduce some side effects like hooking into a package which shouldn't be extended.

So instead of doing:

```php
add_action(
	MyPackage\plugin()->hookName(Package::ACTION_INIT),
	static function(Package $plugin): void {
		$plugin->addModule( ... );
	}
);
```

you simply could loop over your packages by doing:

```php
$packagesToExtend = [
	MyPackage\plugin()
];
foreach($packagesToExtend as $package) {
	add_action(
		$package->hookName(Package::ACTION_INIT),
		static function(Package $plugin): void {
			$plugin->addModule( ... );
		}
	);
}
```

**Comment by shvlv** [comment]
> you simply could loop over your packages by doing:

The problem here is that you don't know whether `MyPackage\plugin()` exists. If the plugin is deactivated, you get fatal. This means we should check it with `function_exists`, which is pretty verbose.

**Comment by gmazzap** [comment]
I think the hook would be good to have.

Looping packages, besides using `function_exists` (which is also not the fastest function in town) has the problem that if you want to target all/most packages, then you might need to edit the function very frequently, e.g. every time a new plugin is added or removed.

Moreover, one issue of calling `MyPackage\plugin()` upfront, is that you might cause that plugin to boot earlier than expected. And if you "wait" using hooks, it might be too late.

To act _as soon as the package is ready_ without side effects is impossible right now, because you need a package instance to add hooks, and obtaining that instance might have side effects.

To help avoid possible unwanted effects, we could fire the hook similarly to:

```php
do_action(
   'inpsyde.modularity.init',
    $package->properties()->basename(),
    $package
);
```

This way, whoever listens to the event could easily filter on the basename. For example:

```php
add_action(
   'inpsyde.modularity.init',
   static function ($basename, Package $package): void {
       if (str_start_with($basename, 'acme-'))  {
           $package->addModule(/* ...*/);
       }
   },
   10,
   2
);
```

This could also be used to build a flexible allow list that you don't need to update often:

```php
const PACKAGES_TO_EXTEND = [
  '(inp)?syde-[a-z\-]+',
  'my-client-[a-z\-]+',
  'something-else',
];

add_action(
   'inpsyde.modularity.init',
   static function ($basename, Package $package): void {
       foreach (PACKAGES_TO_EXTEND as $package) {
         if (preg_match("#$package#", $basename)) {
             $package->addModule(/* ...*/);
             return;
         }
       }
   },
   10,
   2
);
```

If a developer decides to do something with a `Package` instance without checking the package name... that's on them. I mean, we have to trust people to know what they are doing, and if they don't, there are so many different ways they can cause issues...

**Comment by gmazzap** [comment]
@Chrico it seems you agreed on having this hook.

Let's agree on :

- the name
- where exactly to fire it

I was thinking of adding this constant to the class:

```php
public const ACTION_MODULARITY_INIT = self::HOOK_PREFIX . self::ACTION_INIT;
```

The constant evaluates to `"inpsyde.modularity.init"`.

And then do:

```php
do_action(
    self::ACTION_MODULARITY_INIT,
    $this->properties()->baseName(),
    $this
);
```

Immediately after the current [package-specific "init" hook](https://github.com/inpsyde/modularity/blob/c6855a6d9c4ce6f090d031e820f176bddf2a0b1c/src/Package.php#L375).

---

**That said** I was also thinking that we don't have any hook after the package is "built". In 1.7.0 we introduced `built()` but still if we want to hook at that point, which is the first point where it is safe to get a container, we can't do it.

The first point where it is safe to call `$package->container()` is [here](https://github.com/inpsyde/modularity/blob/c6855a6d9c4ce6f090d031e820f176bddf2a0b1c/src/Package.php#L380) but there's no hook there.

If you call `container()` in the current "init" hook or in the new "generic" init hook, you get a fatal error. That is why I was thinking of adding this additional constant to the class:

```php
public const ACTION_INITIALIZED = 'initialized';

```

And then, *after* [the status is "initialized"](https://github.com/inpsyde/modularity/blob/c6855a6d9c4ce6f090d031e820f176bddf2a0b1c/src/Package.php#L380) do something like: 

```php
do_action(
    $this->hookName(self::ACTION_INITIALIZED),
    $this
);
```

I don't think we need a "generic" hook also there. But having a package-specific hook the first moment it is safe to call `$package->container()` I think it is useful.

What you (and everyone) think about this? If you agree, can we have a single PR that address both these two new hooks?

**Comment by Chrico** [comment]
I totally agree with the generic `Package::ACTION_MODULARITY_INIT`-hook. ✔️ 
But, by writing the text below, maybe the name is wrong. The status of the Package is "STATUS_INIT" (does not exists), it is actually `STATUS_IDLE`, so the action should reflect that as well? 😅 

---

> That said I was also thinking that we don't have any hook after the package is "built". In 1.7.0 we introduced built() but still if we want to hook at that point, which is the first point where it is safe to get a container, we can't do it.

I'm wondering what the use case for accessing the container via this hook at this time could be. Maybe we should revisit the workflow of registration, executing, resolving, extending and when which hook makes sense. 

 **v1)** We probably could even use the `Package::progress()` to trigger those hooks (we already have `STATUS_READY` and `ACTION_READY`) so we could have a mapping and automatically trigger those hooks (demo code, not clean):


```php
const STATUS_TO_ACTION = [
	self::STATUS_READY => self::ACTION_READY,
	self::STATUS_INITIALIZED => self::ACTION_INITIALIZED,
];

private function progress(int $status): void
{
	$action = self::STATUS_TO_ACTION[$status] ?? null;
	if($action !== null && !did_action($action)){
		do_action(
			$action, 
			$this->properties()->baseName(),
			$this
		);
	}

	$this->status = $status;
}
```

**v2)** Or we also could implement a similar logic as WordPress has with post_status changes where they have an action which contains "from-to": 

````self::HOOK_PREFIX . ".{$oldStatus}_to_{$newStatus}"````

**v3)** Or - probably not that performant - we implement a 

```php
do_action( self::HOOK_PREFIX . '.progress', $oldStatus, $newStatus, $baseName, $this);
```

**Comment by gmazzap** [comment]
@Chrico I like the idea of emitting a hook on `progress` and I like the idea of having a map between statuses and hooks, even if we might need more statuses than hooks.

Statuses help us determine _internally_ what happened and what is happening, while hooks open the class to the _extern_ and we don't need to expose the class externally at any status change.

For the extern, we only need to expose:

1. a hook to allow external code to _add_ services in the container (via modules or package connection)
2. a hook to allow external code to _get_ staff in the container as soon as it is safe
3. a hook fired when the package is done _executing_ all executable modules

So we have just 3 hooks but more statuses.

I thing we can go with:

1. Package is constructed at `STATUS_IDLE` status
2. Modules are added (or package connected) directly by the code that instantiates the Package. No status change.
3. Build process starts. Status is changed to `STATUS_BUILD_START`
4. `ACTION_BUILD` hook is fired (package specific + global)
5. Build process ends. Status is changed to `STATUS_BUILD_END`
6. `ACTION_BUILT` hook is fired.
7. Boot process starts. Status is changed to `STATUS_BOOT_START`
8. Boot process ends. Status is changed to `STATUS_BOOT_END`
9. `ACTION_BOOTED` hook is fired.
10. Status is changed to `STATUS_DONE`.

This could be done in a 100% backward compatible way, deprecating statuses and actions constants, but keeping them as alias.

So we would have statuses like:

```php
public const STATUS_IDLE = 2;
public const STATUS_BUILD_START = 3;
public const STATUS_BUILD_END = 4;
public const STATUS_BOOT_START = 5;
public const STATUS_BOOT_END = 7;
public const STATUS_DONE = 8;
```

And a "map" like:

```php
private const STATUSES_ACTIONS_MAP = [
    self::STATUS_BUILD_START => self::ACTION_BUILD,
    self::STATUS_BUILD_END => self::ACTION_BUILT
    self::STATUS_BOOT_END => self::ACTION_BOOTED,
];
```

If you agree with this I can send a PR.
